title: Daniel's Blog
description: There will be code
permalink: "/:title/"
theme: minima
exclude: [samples]

# Minima settings
show_excerpts: true
github_username: daniel-aguilar
linkedin_username: dan-aguilar
rss: RSS
